### ISSUE TITLE
Add resizable column on html table

### ISSUE THREAD

**Issue by zoic21** [jeedom/core#2499]

**Comment by jngdan** [comment]
Hi,
I will give more information than only this title (hope it's the same issue... ;-) )
![Variable table](https://github.com/jeedom/core/assets/38414898/fe142f91-78e6-4055-8465-7350d1c5764a)

On the variable table, it's not possible to resized the with of the column name (the first one). Due to this issue, I cannot read the variables names, except for the first 3 or 4 characters, which have a lot more.
This issue is only appears with the last core v4.4.3. 
I suggest a least to resize automatically the with of this column to be able to read the bigger name in this table, as it seems to be for the value column.
Thanks !
